
#
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: clinic_platform_development
  host:  'localhost'
  username: postgres
  password: '123456789'


test:
  <<: *default
  database: clinic_platform_test
  host: 'localhost'
  username: postgres
  password: '123456789'


production:
  <<: *default
  database: clinic_platform_production
  host: 'localhost'
  username: postgres
  password: '123456789'
